# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/79775905-bbd0-4d74-a6fc-4cf5a64ccdaa";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-dda940bf-49c7-4932-a670-c56b61e6e04e".device = "/dev/disk/by-uuid/dda940bf-49c7-4932-a670-c56b61e6e04e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/76F0-04C2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a4891bd8-9e16-492b-87fe-2a2e2bbd0a8d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-480c3a5e-051f-43c1-8306-17842b4326f5".device = "/dev/disk/by-uuid/480c3a5e-051f-43c1-8306-17842b4326f5";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c459f0b4-06bc-4e77-9a33-d8af63c26037"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
