name: Bug Report
description: Report a bug in NitrousOS
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: input
    id: system
    attributes:
      label: System Configuration
      description: Which NitrousOS system are you using?
      placeholder: ex. desktop, server, minimal
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: NitrousOS Version
      description: What version of NitrousOS are you running?
      placeholder: ex. v0.1.0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you encountered
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. Navigate to '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output
      render: shell